services:
  hr-backend:
    image: ${BACKEND_IMAGE:-469049066557.dkr.ecr.ap-south-1.amazonaws.com/cpb/hr-management-backend:latest}
    container_name: hr-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - hr-net

  hr-frontend:
    image: ${FRONTEND_IMAGE:-469049066557.dkr.ecr.ap-south-1.amazonaws.com/cpb/hr-management-frontend:latest}
    container_name: hr-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://hr-api.careerplanb.in}
    networks:
      - hr-net

networks:
  hr-net:
    driver: bridge
